server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:h2:file:./data/authproject;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=myverysecuresecretkeymyverysecuresecretkey123
jwt.expiration=900000

app.admin.name=${ADMIN_NAME:Admin}
app.admin.email=${ADMIN_EMAIL:}
app.admin.password=${ADMIN_PASSWORD:}
