spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:myverysecuresecretkeymyverysecuresecretkey123}
jwt.expiration=${JWT_EXPIRATION:900000}

app.admin.name=${ADMIN_NAME:Admin}
app.admin.email=${ADMIN_EMAIL:admin@example.com}
app.admin.password=${ADMIN_PASSWORD:Admin@123}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://jwt-authentication-system-production.up.railway.app}
